// <auto-generated />
namespace CurrencyExchange.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class addObmennikId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addObmennikId));
        
        string IMigrationMetadata.Id
        {
            get { return "201604281522130_addObmennikId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
